name: Deploy to InfinityFree

on:
  push:
    branches:
      - main # Change this if your default branch is master

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v4

    - name: Sync Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ftpupload.net
        username: ${{ secrets.FTP_if0_42169733}}
        password: ${{ secrets.FTP_yJBfoEeiZ9fj3}}
        local-dir: ./
        server-dir: /htdocs/ # Use /yourdomain.com/htdocs/ if hosting multiple domains
        
