name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v4

    - name: Sync Files via FTP
      uses: SebastianVettel/ftp-action@v2.0.0
      with:
        host: ftpupload.net
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ./
        remoteDir: /livingstoneedu.great-site.net/htdocs/
        
